# Generated by Django 5.0.4 on 2024-04-29 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_link_button_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='destination',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('user', 'destination')},
        ),
    ]
